language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
  - "pypy"
  - "pypy3"
env:
  - PANDAS_VERSION=0.18.2
  - PANDAS_VERSION=0.18.1
  - PANDAS_VERSION=0.18.0
  - PANDAS_VERSION=0.17.0
  - PANDAS_VERSION=0.16.0
  - PANDAS_VERSION=0.15.0
  - PANDAS_VERSION=0.14.0
  - PANDAS_VERSION=0.13.0
  - PANDAS_VERSION=0.12.0
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq r-base
- ./tests/data/load_fixtures.R
# command to install dependencies
install:
  - pip install -q pandas==$PANDAS_VERSION
  - python setup.py install
# command to run tests
script: python setup.py test
